// ESLint flat config wrapping Next's shareable configs (core-web-vitals +
// TypeScript). Run via `npm run lint` (`eslint .`).
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next (triple-slash references included) —
    // linting it only flags Next's own output.
    ignores: ['node_modules/**', '.next/**', 'out/**', 'next-env.d.ts'],
  },
];

export default eslintConfig;
